services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ff
      POSTGRES_PASSWORD: ff
      POSTGRES_DB: ff
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  redis:
    image: redis:7
    ports: [ "6379:6379" ]

  mongo:
    image: mongo:7
    ports: [ "27017:27017" ]
    volumes: [ "mongodata:/data/db" ]

volumes:
  pgdata:
  mongodata:
